✅(add): river queue

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -10,6 +10,7 @@ tasks:
       - task: db-init
       - task: db-migrate
       - task: db-seed
+      - task: river-migrate-up
   check:
     cmds:
       # - task: test-pretty
@@ -75,6 +76,22 @@ tasks:
     cmd: go run cmd/db/main.go db migrate
   db-seed:
     cmd: go run cmd/db/main.go db seed
+  river-migrate-up:
+    cmd: |
+      if ! command -v river &> /dev/null
+      then
+        echo "river could not be found, installing..."
+        go install github.com/riverqueue/river/cmd/river@latest
+      fi
+      river migrate-up --database-url "postgres://postgres:postgres@localhost:5432/trenova_go_db?sslmode=disable"
+  river-ui:
+    cmd: |
+      if ! command -v riverui &> /dev/null
+      then
+        echo "riverui could not be found, installing..."
+        go install riverqueue.com/riverui/cmd/riverui@latest
+      fi
+      DATABASE_URL="postgres://postgres:postgres@localhost:5432/trenova_go_db?sslmode=disable" riverui
   redis-flushall:
     cmd: go run cmd/db/main.go redis flushall
   swag-init:
